FROM python:3.13-slim
WORKDIR /src
COPY pyproject.toml README.md LICENSE ./
COPY tracewake/ tracewake/
RUN pip install --no-cache-dir ".[aws]"
RUN useradd --create-home --uid 10001 tracewake
USER tracewake
ENTRYPOINT ["tracewake-worker"]
